from typing import Dict

from app.agents.base_agent import BaseAgent
from app.services.azure_openai_service import AzureOpenAIService

try:
    from backend.app.prompts.prompt_loader import load_prompt
except ModuleNotFoundError:
    from app.prompts.prompt_loader import load_prompt


class AutomationPolicyAgent(BaseAgent):
    def __init__(self, llm: AzureOpenAIService, process_context: Dict):
        super().__init__(
            agent_id="automation_policy_agent",
            agent_name="Automation Policy Agent",
            llm=llm,
            process_context=process_context,
            guardrails=[
                "Policy decisions must remain AI-derived from process evidence.",
                "Every policy must include Celonis evidence and turnaround impact.",
                "Do not output deterministic static mappings without explanation.",
            ],
        )
        self.prompt_config = load_prompt("automation_policy_agent")

    def process(self, input_data: Dict) -> Dict:
        import json

        policy_seed = self._policy_seed()
        prompt_config = load_prompt(
            "automation_policy_agent",
            input_data_json=json.dumps(input_data, indent=2, default=str),
            policy_seed_json=json.dumps(policy_seed, indent=2, default=str),
            process_context_json=json.dumps(self.process_context, indent=2, default=str),
        )
        result = self.reason_json(
            prompt_config["system_prompt"],
            prompt_config["user_prompt"],
            prompt_purpose="Decide automation policy, route, and human-oversight posture",
            message_bus_input=input_data,
        )
        normalized = self._normalize_result(result)
        handoff = {
            "recommended_agent": normalized.get("recommended_agent"),
            "automation_decision": normalized.get("automation_decision"),
        }
        return self.attach_prompt_trace(normalized, handoff=handoff)

    def _normalize_result(self, result: Dict) -> Dict:
        result = result if isinstance(result, dict) else {}
        result["automation_decision"] = result.get("automation_decision", "MONITOR")
        result["confidence"] = result.get("confidence", 0.0)
        result["risk_level"] = result.get("risk_level", "MEDIUM")
        result["reasoning"] = result.get(
            "reasoning",
            "Generated by GPT-4o from Celonis exception distribution, value, and turnaround context.",
        )
        result["celonis_evidence"] = result.get(
            "celonis_evidence",
            "Uses Celonis exception frequencies, DPO signals, and value-at-risk metrics supplied in prompt context.",
        )
        result["recommended_agent"] = result.get(
            "recommended_agent",
            "Invoice Processing Agent",
        )
        result["human_oversight_needed"] = bool(result.get("human_oversight_needed", False))
        result["exception_specific_policies"] = result.get("exception_specific_policies", {})
        return result

    @staticmethod
    def _policy_seed() -> Dict:
        return {
            "payment_terms_mismatch": {
                "frequency_pct": 100.0,
                "value_usd": 22500000,
                "risk": "MEDIUM",
                "suggested_policy": "AUTOMATE_WITH_MONITORING",
            },
            "invoice_exception": {
                "frequency_pct": 51.4,
                "value_usd": 2480000,
                "risk": "HIGH",
                "suggested_policy": "HUMAN_REQUIRED for complex, AUTO for known high-confidence patterns",
            },
            "short_payment_terms": {
                "frequency_pct": 67.6,
                "value_usd": 15300000,
                "risk": "CRITICAL",
                "suggested_policy": "AUTO_ESCALATE",
            },
            "early_payment": {
                "frequency_pct": 62.2,
                "value_usd": 19000000,
                "risk": "LOW",
                "suggested_policy": "AUTOMATE",
            },
            "open_invoices": {
                "frequency_pct": 10.8,
                "value_usd": 2960000,
                "risk": "MEDIUM",
                "suggested_policy": "AUTOMATE",
            },
            "paid_late": {
                "frequency_pct": 29.7,
                "value_usd": 5410000,
                "risk": "HIGH",
                "suggested_policy": "ANALYZE",
            },
        }
