from typing import Dict

from app.agents.base_agent import BaseAgent
from app.services.azure_openai_service import AzureOpenAIService

try:
    from backend.app.prompts.prompt_loader import load_prompt
except ModuleNotFoundError:
    from app.prompts.prompt_loader import load_prompt


class AutomationPolicyAgent(BaseAgent):
    def __init__(self, llm: AzureOpenAIService, process_context: Dict):
        super().__init__(
            agent_id="automation_policy_agent",
            agent_name="Automation Policy Agent",
            llm=llm,
            process_context=process_context,
            guardrails=[
                "Policy decisions must remain AI-derived from process evidence.",
                "Every policy must include Celonis evidence and turnaround impact.",
                "Do not output deterministic static mappings without explanation.",
            ],
        )
        self.prompt_config = load_prompt("automation_policy_agent")

    def process(self, input_data: Dict) -> Dict:
        import json

        policy_seed = self._policy_seed()
        prompt_config = load_prompt(
            "automation_policy_agent",
            input_data_json=json.dumps(input_data, indent=2, default=str),
            policy_seed_json=json.dumps(policy_seed, indent=2, default=str),
            process_context_json=json.dumps(self.process_context, indent=2, default=str),
        )
        result = self.reason_json(
            prompt_config["system_prompt"],
            prompt_config["user_prompt"],
            prompt_purpose="Decide automation policy, route, and human-oversight posture",
            message_bus_input=input_data,
        )
        normalized = self._normalize_result(result)
        self._provenance_tag(normalized)
        handoff = {
            "recommended_agent": normalized.get("recommended_agent"),
            "automation_decision": normalized.get("automation_decision"),
        }
        return self.attach_prompt_trace(normalized, handoff=handoff)

    def _normalize_result(self, result: Dict) -> Dict:
        result = result if isinstance(result, dict) else {}
        result["automation_decision"] = result.get("automation_decision", "MONITOR")
        result["confidence"] = result.get("confidence", 0.0)
        result["risk_level"] = result.get("risk_level", "MEDIUM")
        result["reasoning"] = result.get(
            "reasoning",
            "Generated by GPT-4o from Celonis exception distribution, value, and turnaround context.",
        )
        result["celonis_evidence"] = result.get(
            "celonis_evidence",
            "Celonis context was provided in prompt; LLM did not return specific evidence citation."
            if self._context_available()
            else "[Celonis data unavailable for this request]",
        )
        result["recommended_agent"] = result.get(
            "recommended_agent",
            "Invoice Processing Agent",
        )
        result["human_oversight_needed"] = bool(result.get("human_oversight_needed", False))
        result["exception_specific_policies"] = result.get("exception_specific_policies", {})
        return result

    def _policy_seed(self) -> Dict:
        """Build policy seed from live process_context exception patterns. No hardcoded values."""
        ctx = self.process_context or {}
        exception_patterns = ctx.get("exception_patterns", [])
        seed = {}
        for pat in exception_patterns:
            exc_type = str(pat.get("exception_type", "")).lower()
            key = exc_type.replace(" ", "_").replace("(", "").replace(")", "")
            if not key:
                continue
            freq = float(pat.get("frequency_percentage", 0) or 0)
            seed[key] = {
                "frequency_pct": freq,
                "value_usd": 0.0,
                "risk": "CRITICAL" if freq >= 60 else "HIGH" if freq >= 40 else "MEDIUM" if freq >= 20 else "LOW",
                "suggested_policy": "HUMAN_REQUIRED" if freq >= 60 else "MONITOR" if freq >= 40 else "AUTOMATE_WITH_MONITORING",
                "_data_source": "celonis",
            }
        if not seed:
            seed["_empty"] = {
                "frequency_pct": 0.0,
                "value_usd": 0.0,
                "risk": "UNKNOWN",
                "suggested_policy": "MONITOR",
                "_data_source": "unavailable",
            }
        return seed
