from typing import Dict

from app.agents.base_agent import BaseAgent
from app.services.azure_openai_service import AzureOpenAIService

try:
    from backend.app.prompts.prompt_loader import load_prompt
except ModuleNotFoundError:
    from app.prompts.prompt_loader import load_prompt


class PromptWriterAgent(BaseAgent):
    def __init__(self, llm: AzureOpenAIService, process_context: Dict):
        super().__init__(
            agent_id="prompt_writer_agent",
            agent_name="Prompt Writer Agent",
            llm=llm,
            process_context=process_context,
            guardrails=[
                "Every generated prompt must cite concrete Celonis evidence and turnaround impact.",
                "No deterministic rule trees; prompts must ask the target LLM to reason from process context.",
                "All four exception families must be covered: terms mismatch, invoice exception, short terms, early payment.",
            ],
        )
        self.prompt_config = load_prompt("prompt_writer_agent")

    def process(self, input_data: Dict) -> Dict:
        import json

        target_agent = input_data.get("target_agent", "Exception Agent")
        scenario = input_data.get(
            "scenario",
            "Generate evidence-grounded prompts for handling P2P exceptions.",
        )

        known_facts = self._known_celonis_facts()
        prompt_config = load_prompt(
            "prompt_writer_agent",
            target_agent=target_agent,
            scenario=scenario,
            input_data_json=json.dumps(input_data, indent=2, default=str),
            known_facts_json=json.dumps(known_facts, indent=2, default=str),
            process_context_json=json.dumps(self.process_context, indent=2, default=str),
        )
        result = self.reason_json(
            prompt_config["system_prompt"],
            prompt_config["user_prompt"],
            prompt_purpose=f"Generate downstream prompts for {target_agent}",
            message_bus_input=input_data,
        )
        normalized = self._normalize_result(result, target_agent)
        self._provenance_tag(normalized)
        handoff = {
            "target_agent": target_agent,
            "generated_prompt_keys": list((normalized.get("generated_prompts", {}) or {}).keys()),
        }
        return self.attach_prompt_trace(normalized, handoff=handoff)

    def _normalize_result(self, result: Dict, target_agent: str) -> Dict:
        generated = result.get("generated_prompts", {}) if isinstance(result, dict) else {}
        result = result if isinstance(result, dict) else {}
        result["target_agent"] = result.get("target_agent", target_agent)
        result["generated_prompts"] = generated
        result["celonis_evidence"] = result.get(
            "celonis_evidence",
            "Celonis context was provided in prompt; LLM did not return specific evidence citation."
            if self._context_available()
            else "[Celonis data unavailable for this request]",
        )
        result["ai_reasoning"] = result.get(
            "ai_reasoning",
            "Prompts are generated by GPT-4o from process mining evidence and turnaround context.",
        )
        return result

    def _known_celonis_facts(self) -> Dict:
        """Extract portfolio and exception facts from live process_context. No hardcoded values."""
        ctx = self.process_context or {}
        exception_patterns = ctx.get("exception_patterns", [])
        has_data = self._context_available()

        total_cases = int(ctx.get("total_cases", 0) or 0)
        avg_dpo = float(ctx.get("avg_end_to_end_days", 0) or 0)

        exceptions = {}
        for pat in exception_patterns:
            exc_type = str(pat.get("exception_type", "")).lower()
            key = exc_type.replace(" ", "_").replace("(", "").replace(")", "")
            if not key:
                continue
            exceptions[key] = {
                "affected_invoices": int(pat.get("affected_cases", 0) or 0),
                "percentage": float(pat.get("frequency_percentage", 0) or 0),
                "value_usd": 0.0,
                "avg_dpo_days": float(pat.get("avg_resolution_time_days", 0) or 0),
                "_data_source": "celonis",
            }

        return {
            "portfolio": {
                "total_invoices": total_cases,
                "total_invoice_value_usd": 0.0,
                "avg_dpo_days": avg_dpo,
                "value_at_risk_usd": 0.0,
                "_data_source": "celonis" if has_data else "unavailable",
            },
            "exceptions": exceptions if exceptions else {"_empty": {"_data_source": "unavailable"}},
        }
