from typing import Dict

from app.agents.base_agent import BaseAgent
from app.services.azure_openai_service import AzureOpenAIService


class PromptWriterAgent(BaseAgent):
    def __init__(self, llm: AzureOpenAIService, process_context: Dict):
        super().__init__(
            agent_id="prompt_writer_agent",
            agent_name="Prompt Writer Agent",
            llm=llm,
            process_context=process_context,
            guardrails=[
                "Every generated prompt must cite concrete Celonis evidence and turnaround impact.",
                "No deterministic rule trees; prompts must ask the target LLM to reason from process context.",
                "All four exception families must be covered: terms mismatch, invoice exception, short terms, early payment.",
            ],
        )

    def process(self, input_data: Dict) -> Dict:
        import json

        target_agent = input_data.get("target_agent", "Exception Agent")
        scenario = input_data.get(
            "scenario",
            "Generate evidence-grounded prompts for handling P2P exceptions.",
        )

        known_facts = self._known_celonis_facts()
        system_prompt = f"""
You are Prompt Writer Agent for AI-driven P2P automation.
You are writing prompts for downstream AI agents, not deciding outcomes directly.
You MUST use Celonis evidence from the provided process context and known metrics.

Return strict JSON with this exact shape:
{{
  "target_agent": "{target_agent}",
  "generated_prompts": {{
    "system_prompt": "...",
    "exception_specific_prompts": {{
      "payment_terms_mismatch": {{
        "detection_prompt": "...",
        "resolution_prompt": "...",
        "celonis_evidence": "..."
      }},
      "invoice_exception": {{
        "detection_prompt": "...",
        "resolution_prompt": "...",
        "celonis_evidence": "..."
      }},
      "short_payment_terms": {{
        "detection_prompt": "...",
        "resolution_prompt": "...",
        "celonis_evidence": "..."
      }},
      "early_payment_optimization": {{
        "detection_prompt": "...",
        "resolution_prompt": "...",
        "celonis_evidence": "..."
      }}
    }},
    "workflow_instructions": [
      {{
        "step": 1,
        "instruction": "...",
        "celonis_evidence": "...",
        "ai_reasoning": "..."
      }}
    ],
    "decision_logic": [
      {{
        "scenario": "...",
        "ai_recommendation": "...",
        "confidence": 0.0,
        "celonis_evidence": "...",
        "ai_reasoning": "..."
      }}
    ],
    "guardrails": [
      {{
        "constraint": "...",
        "celonis_evidence": "...",
        "enforcement": "BLOCK|ESCALATE|WARN",
        "ai_reasoning": "..."
      }}
    ]
  }},
  "celonis_evidence": "...",
  "ai_reasoning": "..."
}}

Strict requirements:
1. Must include explicit prompt instructions for all four exception families.
2. Must include turnaround-time awareness in prompts.
3. Must reflect AI-driven reasoning and avoid hardcoded if/else language.
4. Each section must cite Celonis evidence, including numeric values where available.
"""

        user_prompt = f"""
Target agent: {target_agent}
Scenario: {scenario}
Input payload:
{json.dumps(input_data, indent=2, default=str)}

Known Celonis metrics:
{json.dumps(known_facts, indent=2, default=str)}

Full process_context:
{json.dumps(self.process_context, indent=2, default=str)}

Create high-quality prompts that explicitly cover:
- Payment terms mismatch (invoice vs PO vs vendor master, 37 invoices, 22.5M, avg DPO 36.52)
- Invoices with exception (19 invoices, 2.48M, DPO 80.83 critical)
- Short payment terms 0-day (25 invoices, 15.3M, DPO 1.21)
- Early payment optimization (23 invoices, 19M, DPO 3.08 vs potential 63)
"""
        result = self.reason_json(
            system_prompt,
            user_prompt,
            prompt_purpose=f"Generate downstream prompts for {target_agent}",
            message_bus_input=input_data,
        )
        normalized = self._normalize_result(result, target_agent)
        handoff = {
            "target_agent": target_agent,
            "generated_prompt_keys": list((normalized.get("generated_prompts", {}) or {}).keys()),
        }
        return self.attach_prompt_trace(normalized, handoff=handoff)

    def _normalize_result(self, result: Dict, target_agent: str) -> Dict:
        generated = result.get("generated_prompts", {}) if isinstance(result, dict) else {}
        result = result if isinstance(result, dict) else {}
        result["target_agent"] = result.get("target_agent", target_agent)
        result["generated_prompts"] = generated
        result["celonis_evidence"] = result.get(
            "celonis_evidence",
            "Derived from Celonis process context and exception/value metrics included in prompt input.",
        )
        result["ai_reasoning"] = result.get(
            "ai_reasoning",
            "Prompts are generated by GPT-4o from process mining evidence and turnaround context.",
        )
        return result

    @staticmethod
    def _known_celonis_facts() -> Dict:
        return {
            "portfolio": {
                "total_invoices": 37,
                "total_invoice_value_usd": 22500000,
                "avg_dpo_days": 36.52,
                "max_possible_dpo_days": 50,
                "value_at_risk_usd": 5000000,
            },
            "exceptions": {
                "payment_terms_mismatch": {
                    "affected_invoices": 37,
                    "percentage": 100.0,
                    "value_usd": 22500000,
                    "avg_dpo_days": 36.52,
                },
                "invoice_exception": {
                    "affected_invoices": 19,
                    "percentage": 51.4,
                    "value_usd": 2480000,
                    "avg_dpo_days": 80.83,
                },
                "short_payment_terms_0_days": {
                    "affected_invoices": 25,
                    "percentage": 67.6,
                    "value_usd": 15300000,
                    "avg_dpo_days": 1.21,
                },
                "early_payment_dpo_0_7": {
                    "affected_invoices": 23,
                    "value_usd": 19000000,
                    "actual_dpo_days": 3.08,
                    "potential_dpo_days": 63,
                    "value_potential_usd": 2000000,
                },
            },
        }
