from typing import Dict

from app.agents.base_agent import BaseAgent
from app.services.azure_openai_service import AzureOpenAIService

try:
    from backend.app.prompts.prompt_loader import load_prompt
except ModuleNotFoundError:
    from app.prompts.prompt_loader import load_prompt


class PromptWriterAgent(BaseAgent):
    def __init__(self, llm: AzureOpenAIService, process_context: Dict):
        super().__init__(
            agent_id="prompt_writer_agent",
            agent_name="Prompt Writer Agent",
            llm=llm,
            process_context=process_context,
            guardrails=[
                "Every generated prompt must cite concrete Celonis evidence and turnaround impact.",
                "No deterministic rule trees; prompts must ask the target LLM to reason from process context.",
                "All four exception families must be covered: terms mismatch, invoice exception, short terms, early payment.",
            ],
        )
        self.prompt_config = load_prompt("prompt_writer_agent")

    def process(self, input_data: Dict) -> Dict:
        import json

        target_agent = input_data.get("target_agent", "Exception Agent")
        scenario = input_data.get(
            "scenario",
            "Generate evidence-grounded prompts for handling P2P exceptions.",
        )

        known_facts = self._known_celonis_facts()
        prompt_config = load_prompt(
            "prompt_writer_agent",
            target_agent=target_agent,
            scenario=scenario,
            input_data_json=json.dumps(input_data, indent=2, default=str),
            known_facts_json=json.dumps(known_facts, indent=2, default=str),
            process_context_json=json.dumps(self.process_context, indent=2, default=str),
        )
        result = self.reason_json(
            prompt_config["system_prompt"],
            prompt_config["user_prompt"],
            prompt_purpose=f"Generate downstream prompts for {target_agent}",
            message_bus_input=input_data,
        )
        normalized = self._normalize_result(result, target_agent)
        handoff = {
            "target_agent": target_agent,
            "generated_prompt_keys": list((normalized.get("generated_prompts", {}) or {}).keys()),
        }
        return self.attach_prompt_trace(normalized, handoff=handoff)

    def _normalize_result(self, result: Dict, target_agent: str) -> Dict:
        generated = result.get("generated_prompts", {}) if isinstance(result, dict) else {}
        result = result if isinstance(result, dict) else {}
        result["target_agent"] = result.get("target_agent", target_agent)
        result["generated_prompts"] = generated
        result["celonis_evidence"] = result.get(
            "celonis_evidence",
            "Derived from Celonis process context and exception/value metrics included in prompt input.",
        )
        result["ai_reasoning"] = result.get(
            "ai_reasoning",
            "Prompts are generated by GPT-4o from process mining evidence and turnaround context.",
        )
        return result

    @staticmethod
    def _known_celonis_facts() -> Dict:
        return {
            "portfolio": {
                "total_invoices": 37,
                "total_invoice_value_usd": 22500000,
                "avg_dpo_days": 36.52,
                "max_possible_dpo_days": 50,
                "value_at_risk_usd": 5000000,
            },
            "exceptions": {
                "payment_terms_mismatch": {
                    "affected_invoices": 37,
                    "percentage": 100.0,
                    "value_usd": 22500000,
                    "avg_dpo_days": 36.52,
                },
                "invoice_exception": {
                    "affected_invoices": 19,
                    "percentage": 51.4,
                    "value_usd": 2480000,
                    "avg_dpo_days": 80.83,
                },
                "short_payment_terms_0_days": {
                    "affected_invoices": 25,
                    "percentage": 67.6,
                    "value_usd": 15300000,
                    "avg_dpo_days": 1.21,
                },
                "early_payment_dpo_0_7": {
                    "affected_invoices": 23,
                    "value_usd": 19000000,
                    "actual_dpo_days": 3.08,
                    "potential_dpo_days": 63,
                    "value_potential_usd": 2000000,
                },
            },
        }
